### ISSUE TITLE
Lab - Inconsistent Data in Cells, SSE/SST/SSR relationship not consistant

### ISSUE THREAD

**Issue by benjamin-jacobson** [learn-co-curriculum/dsc-coefficient-of-determination-lab#1]
The "toy data" does not return a consistent result (the numbers defined are not the same in the array in different cells, and the mean of the data seems to be throwing off the calculation.)

These do not calculate correctly as a results for these:

print(SSR/SST) #should be r^2
print(1 - (SSE/SST)) #should be r^2
print((SST-SSR-SSE).round(0)) #should be 0

**Comment by hoffm386** [comment]
This should be resolved by https://github.com/learn-co-curriculum/dsc-coefficient-of-determination-lab/commit/1e55666720a854fcb6c92042c4a82111267d2594, which removed the repeated variable declarations
